[workspace]
members = [
    "crates/*",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Radroots <info@radroots.dev>"]
license = "AGPLv3"
description = "rhizome is a Nostr data vending machine (NIP-90)"
